### ISSUE TITLE
Force create and update plan, add-on and discount to be done in Reepay Admin

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#11]
1. When connecting plans to products, show it like in the picture. Dropdown to choose the plan. Use the get list of plans API to get all the plans. If the merchant click **Refresh list** we will call get list of plan API again. If they click the **Create new plan** button they will simply be redirected to Reepay admin (http://app.reepay.com/#/rp/config/plans/create). We will show all the info from the selected plan, but this can not be changed. When merchants are ready to connect the plan to the product, they click on the **Save plan to product** button. When they click on Save plan to the product we save all the plan data to the product. If there is already existing data, we simply overwrite the data.

2. Similar approach and design for add-ons. Remember also the add-ons which you can apply for shipping. Link to **Create new add-on** is: https://app.reepay.com/#/rp/config/addons/create

3. Similar approach and design for coupons. Link to **Create new discount** is https://app.reepay.com/#/rp/config/discounts/create

![image](https://user-images.githubusercontent.com/49717740/203983025-8bc5d13e-569a-46d0-a0de-22b659234900.png)

![image](https://user-images.githubusercontent.com/49717740/203983041-fda85aa4-9ced-4fcf-8f57-dcffec546815.png)

**Comment by dimaspolohov** [comment]
Plan details is not showing up when you select one of the plans. Also I can see the Refresh list button refresh the entire site. Either the button should simply call the get list of plans again, or we should not have the button at all.
https://reepay.slack.com/files/UAA5K92LC/F04DRQM36RH/screen_recording_2022-12-05_at_14.47.39.mov

**Comment by dimaspolohov** [comment]
Can we make these dropdown more narrow so the buttons "Refresh list" and "Create new add-on" can be on same line?
Also it seems like the drop down from add-ons section have been given some custom padding. This should be deleted.
We also need some changes to plan view on variable product. Please see picture. For bottom border use following styling:

border-bottom-style: solid;
border-bottom-width: 1px;
border-bottom-color: #c3c4c7;

Please send me a screen shot when you have fixed this. (edited) 



![Image](https://user-images.githubusercontent.com/81742762/205904740-dc6ac7a0-afc8-495b-8cb5-7ed8a1f5d34d.png)



![Image](https://user-images.githubusercontent.com/81742762/205904769-d83408a1-a454-416e-987e-58393fb7e250.png)

**Comment by dimaspolohov** [comment]
This separator should move up here:

![Image](https://user-images.githubusercontent.com/81742762/205904871-e1400d41-f37a-4754-8a79-662d009a44c4.png)
