### ISSUE TITLE
Support for WooCommerce Memberships

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#12]

**Comment by dimaspolohov** [comment]
@markusbrunke Can you give more details about this task?

**Comment by markusbrunke** [comment]
@dimaspolohov We need to support this plugin: https://woocommerce.com/products/woocommerce-memberships/. 

If you install this plugin and WooCommerce Subscription, I think you are able to see how WooCommerce Subscription works with WooCommerce Membership. We need to have kind of the same.

**Comment by markusbrunke** [comment]
Maybe this is helpful as well: https://woocommerce.com/document/woocommerce-memberships-subscriptions-integration/
