### ISSUE TITLE
Link Subscription menu option to Reepay Admin

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#18]
![image](https://user-images.githubusercontent.com/49717740/205073371-0a70642a-3f34-4dc1-93ee-dc92d9b73dba.png)

**Comment by dimaspolohov** [comment]
@markusbrunke Subscriptions is linked, on you screenshot list must be not empty?

**Comment by markusbrunke** [comment]
@dimaspolohov It's a easy one. The "Subscription" menu should just link to https://app.reepay.com/#/rp/subscriptions

**Comment by markusbrunke** [comment]
@dimaspolohov I can see this is opening reepay in the existing tab. It has to open i a new tab 

![Image](https://user-images.githubusercontent.com/49717740/207837931-ef999325-3f6b-4542-a868-4eb211b2a8cf.png)

**Comment by markusbrunke** [comment]
Still not work: 

![Image](https://user-images.githubusercontent.com/49717740/214080686-b39ed509-62a6-4dcb-8962-01b44779a452.png)

**Comment by dimaspolohov** [comment]
@markusbrunke You mean the new tab?

**Comment by markusbrunke** [comment]
When click the "Subscription" menu option, we should open https://app.reepay.com/#/rp/subscriptions in a new tab. We don't need the page I have in my screenshot above.
