### ISSUE TITLE
Plan view alignment

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#25]
Align the plan view. See the screenshots below. Please send me a screenshot before you do the pull request:

![Image](https://user-images.githubusercontent.com/49717740/206283409-f9befd70-0450-41f7-af52-f39b2fe6d9a5.png)

All these are in the same container. They should be in 3 separate containers like all other lines.

![Image](https://user-images.githubusercontent.com/49717740/206283557-66779103-9cf8-46b7-aedd-1a8eb5ce4b0f.png)

No trial information is displayed.

![Image](https://user-images.githubusercontent.com/49717740/206283730-54a5d650-539b-4a08-8f09-f219684d05d0.png)

**Comment by markusbrunke** [comment]
Also change "Subscription pricing" to "Price"
Also change "Setup Fee" to "Setup fee"
Also change "Minimum Contract Period" to "Minimum contract period"
Also change "Default Quantity" to "Default quantity"
Also change "Schedule Type" to "Scheduly type"

**Comment by markusbrunke** [comment]
![Image](https://user-images.githubusercontent.com/49717740/206291304-3ae4632b-fcea-4b2b-9f26-6db0b116735f.png)

**Comment by Daniel217D** [comment]
Updated plan template

![Image](https://user-images.githubusercontent.com/26818342/206318785-98b85356-7f6b-426e-bc0c-f0a932844888.png)



![Image](https://user-images.githubusercontent.com/26818342/206318789-e28bef94-c67a-42d5-9374-9930071f8d42.png)

**Comment by markusbrunke** [comment]
@Daniel217D are we getting the currency from the Reepay account?

**Comment by Daniel217D** [comment]
@Daniel217D Hi,
About currency - Now yes, but before the currency was taken from Woocommerce, so Woocommerce products need to be resaved to display the currency. For new products, everything will be fine right away
Text changes made

**Comment by Daniel217D** [comment]
Can I create a pr?

**Comment by Daniel217D** [comment]
View after testing and fixes

![Image](https://user-images.githubusercontent.com/26818342/206956881-e14b9667-ab87-4dce-9433-f3b476650542.png)



![Image](https://user-images.githubusercontent.com/26818342/206956894-c462f26c-da75-4daa-b509-15c28faa4fd0.png)
