### ISSUE TITLE
Display subscription link on renewals

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#28]
![Image](https://user-images.githubusercontent.com/49717740/206414976-c0b12b84-7d02-49fc-87e5-60c1e1d40852.png)

**Comment by Daniel217D** [comment]
Or this way?

![Image](https://user-images.githubusercontent.com/26818342/206957201-c458888e-a9cd-4075-9a33-8d74d4750a62.png)
