### ISSUE TITLE
Mixed up strings

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#39]
_We had trouble with "Billed every. month" and "Billed every month on the first day of month"? They had these two strings mixed up, so I had to "cheat" translating them so that our website (cart) would say "Billed every month" when that option was selected. I've noticed that this issue remains_

**Comment by dimaspolohov** [comment]
@markusbrunke Now labels is setup like this, can you say whats wrong?

![Image](https://user-images.githubusercontent.com/81742762/213158112-8f7c481c-eda2-48c9-8d21-69689550240a.png)

**Comment by markusbrunke** [comment]
Yes.

Month(s) = Every x month on this day (the day the customer signs up)
Fixed day of month = Every x month on x day of the month
Last day of month = Every x month on the last day of the month
