### ISSUE TITLE
Issue with double charging

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#42]
Customer feedback: 

We are experiencing double invoicing, however, it is a special case test card with CVC 202,

"The second payment is declined with a recoverable error (insufficient funds)"
When reepay tries to withdraw money #113, the invoice order in WooCommerce is set to fail because there was not enough money. Just after the customer corrects his payment card details after receiving the dunning email which means the failed invoice #113 getting settled in Reepay.

The new settled status does not appear in WooCommerce on the Renewal order, but instead, an invoice is now created 5 minutes after #114 which also settles, it enters WooCommerce.

I can see that when the customer corrects the payment information, the reepay plugin subscription changes the order back to the status "Completed", which is our signal to the plugin that it should start the subscription.

So here a loop happens. But there shouldn't be a check to see if the subscription hasn't already started.

![Image](https://user-images.githubusercontent.com/49717740/212714323-312d3334-cb0e-4602-a71a-6e773344a996.png)

**Comment by dimaspolohov** [comment]
@markusbrunke Hi, can you give more info on how we can reproduce this?
with 202 CVC invoice was success created
May be screencast?

**Comment by markusbrunke** [comment]
@dimaspolohov Please see this: https://reference.reepay.com/api/#searching-and-pagination
