### ISSUE TITLE
Many small errors, enhancements etc.

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-subscriptions#45]
1. Add standard spacing

![Image](https://user-images.githubusercontent.com/49717740/214038019-0ceccb8a-1cc9-4738-9e88-bd238f6b7a11.png)

2. Can we get the plan preview to update automatically when a plan has been selected in the drop-down? Of course, you still need to click save, but so that you can see the plan details.

https://user-images.githubusercontent.com/49717740/214038242-f31e955f-fcb0-4d78-a617-e873191d7eea.mov

3. Add-on view is weird:

![Image](https://user-images.githubusercontent.com/49717740/214038396-592d7e32-d9d8-4f29-ae26-f3e9fe1af1f7.png)

4. Missing widgets on renewal orders, old buttons for see customer, invoice and subscription still appear, logos for payment methods in invoice widgets does not appear

https://user-images.githubusercontent.com/49717740/214039014-5a25ce00-1e39-430b-a4fa-a72369b40b0e.mov

**Comment by dimaspolohov** [comment]
@markusbrunke About 4 points - widget must be able for all repay orders or only for subscriptions and renewals?
We must remove old buttons everywhere?

**Comment by markusbrunke** [comment]
@dimaspolohov All reepay orders.

Regular orders = Customer widget, invoice widget
Renewal orders = Customer widget, invoice widget, subscription widget
Subscription orders = Customer widget, subscription widget
