### ISSUE TITLE
Add card to order

### ISSUE THREAD

**Issue by dimaspolohov** [reepay/reepay-woocommerce-subscriptions#61]
What I meant was to create custom fields on the order for card type and credit card number.

We have a merchant who is trying to import some credit cards on his existing Wordpress customers. He is adding the card reference ca_xxxxxxxxxx on the right field in our plugin for each customers, but he can't get it to work. How do merchant normally do, when they witch out their payment gateway provider and are using WooCommerce Subscriptions? So news card references needs to be updated in WooCommerce

**Comment by Daniel217D** [comment]
@markusbrunke 
Did we understand correctly that a form is required on the order page to change the card token? We implemented it like this:


![Image](https://user-images.githubusercontent.com/26818342/232799495-07d3c7fd-488c-4c76-a46c-c8da65aa2f09.png)

With this implementation, the question arose of which tokens would be used. Only reepay tokens or is it possible to support tokens of other payment systems?

If this implementation is incorrect, then we need more information to understand the problem.

**Comment by markusbrunke** [comment]
@Daniel217D Sorry, it's incorrect.

We have already added the credit card information in the custom fields. We do this each time we have an order paid with a saved credit card. What we are missing is we also need to add this information for regular orders where you are not using a saved credit card.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/49717740/232804081-d5bb59f1-ddd3-4b88-853e-9670ef465a4b.png">

**Comment by markusbrunke** [comment]
So reepay_card_type and reepay_masked_card should also be added to custom fields for regular orders where non-saved payment cards is being used

**Comment by dimaspolohov** [comment]
@markusbrunke That's done
